### ISSUE TITLE
Request for tagged release on GitHub for bioconda integration

### ISSUE THREAD

**Issue by nickp60** [pirovc/fgap#1]
Hi, I am trying to add FGAP to bioconda, but they require either compiled versions (not usable in this case, due to the licensing of the matlab runtime), or that a git repo has a tagged release.  Would you be able to make a tagged release via GitHub for v1.8.1?  
[Here are the notes](https://bioconda.github.io/linting.html#uses-git-url) on the need for a tagged release.

Thanks in advance!

**Comment by pirovc** [comment]
Hi,

Sure, I just did it: https://github.com/pirovc/fgap/releases/tag/fgap_v1.8.1
Please let me know if you need some help, I also work with bioconda.

Vitor

**Comment by nickp60** [comment]
Thanks so much!  Ill reference this release with the next conda recipe update.
