### ISSUE TITLE
 Query Coverage

### ISSUE THREAD

**Issue by jamescjc123** [pirovc/fgap#2]
hi, FGAP is a very useful tool. i have a question about the results. The log file has the query coverage of the alignment,  but some query coverage are very low(15%~). How can i filter the query coverage?

**Comment by pirovc** [comment]
Hi @chaijinchao,

On the current version there's no way to filter out results by query coverage directly. However, you can control somehow the query coverage by increasing the parameter:

`-s /--min-score		Min Score (raw) to return results from BLAST (integer) - Default: 25`

which accounts for the raw score and can reach the maximum value defined by the contig end length `-C /--contig-end-length` (default 300) with match score of 1 (default `-l /--blast-alignment-parameters`).

If you are using the source-code version, you could also add the following code to the line 472:
`' -qcov_hsp_perc 100' ...`
with a value between 0 and 100, which will filter your results also by query coverage.

Best,
Vitor

**Comment by jamescjc123** [comment]
thank you! i will try it.
