### ISSUE TITLE
Can I run this step by step? 

### ISSUE THREAD

**Issue by YangJianshun** [pirovc/fgap#4]
I have run this program with the default parameters. It took a day to get the blastn.out file. Now I want to change the parameters -R and -I, but must I re-run the blastn process?

Thank you

**Comment by pirovc** [comment]
Hi Yang,

Unfortunatelly such functionallity is not available. I would recommend first to work with sub-set of your files until you find the correct parameters and then execute FGAP with the complete data.

Vitor
