### ISSUE TITLE
--eval "CODE"

### ISSUE THREAD

**Issue by fabio-marcelo** [pirovc/fgap#5]
Hi.
I've been trying to run fgap and I've got the following issue:
$ bash ~/project_1/script_projeto_1/fgap.sh 
+ cd spades.contig_mob_fgap
+ top1=_spades-contigs.chromosome.fasta
+ array=("SRR7284655")
+ for i in '${array[@]}'
+ pathtop1=/home/fabio/project_1/compila_contigs/spades.contigs_mob/SRR7284655_spades-contigs.fastaout
+ dataset=/home/fabio/project_1/compila_contigs/SRR7284655.contigs_a5_raw_trimo15.fasta
++ FGAP -d /home/fabio/project_1/compila_contigs/spades.contigs_mob/SRR7284655_spades-contigs.fastaout/SRR7284655_spades-contigs.chromosome.fasta -a ''\''/home/fabio/project_1/compila_contigs/SRR7284655.contigs_a5_raw_trimo15.fasta'\''' -o SRR7284655_top1_fgap/SRR7284655_fgap_output -b blastn
warning: --eval "CODE" and script file are mutually exclusive options

Can you help me please?
Best regards.

**Comment by pirovc** [comment]
Hi @fabio-marcelo 

Can you share more information on your issue? What was your command line call and what is the error message? I can't really help with the information given.

Best
Vitor
