### ISSUE TITLE
Error while running fgap with sample data

### ISSUE THREAD

**Issue by kishore556** [pirovc/fgap#7]
I was trying to run the fgap with sample data but received error "Error: libncurses.so.5: cannot open shared object file: No such file or directory"
the details is as follows
acer@kishor:~/FGAP$ ./run_fgap.sh  /home/acer/MCR/v717/ -d sample_data/DRAFT_ecoli_hiseq454.fasta -a sample_data/DATASET_ecoli_hiseq.fasta
------------------------------------------
Setting up environment variables
---
LD_LIBRARY_PATH is .:/home/acer/MCR/v717//runtime/glnxa64:/home/acer/MCR/v717//bin/glnxa64:/home/acer/MCR/v717//sys/os/glnxa64:/home/acer/MCR/v717//sys/java/jre/glnxa64/jre/lib/amd64/native_threads:/home/acer/MCR/v717//sys/java/jre/glnxa64/jre/lib/amd64/server:/home/acer/MCR/v717//sys/java/jre/glnxa64/jre/lib/amd64/client:/home/acer/MCR/v717//sys/java/jre/glnxa64/jre/lib/amd64
An Error has occurred while trying to initialize the MCR.  
The error is: Fatal error loading library /home/acer/MCR/v717/bin/glnxa64/libmwmclmcr.so Error: libncurses.so.5: cannot open shared object file: No such file or directory
Error:mclmcr initialization failed

**Comment by pirovc** [comment]
I guess it's a problem with the MCR installation. Do you have the libncurses installed in your system? Alternatively you can use the bioconda version that uses octave instead of MCR to run FGAP.

Cheers
Vitor

**Comment by kishore556** [comment]
Thanks
the problem was solved by creating soft link of libncurses.so.5 to folder /MCR/v717/bin/glnxa64/ from system
I just facing another problem of "Error MAKEBLASTDB path: makeblastdb: /home/acer/MCR/v717//sys/os/glnxa64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by makeblastdb)"
But the 'libstdc++.so.6' is present in the system.
Attaching the error shown ----
[Error_FGAP_24042021.txt](https://github.com/pirovc/fgap/files/6369449/Error_FGAP_24042021.txt)

**Comment by pirovc** [comment]
It looks like the blast is not properly installed in the system. Can you run the makeblastdb command outside fgap? You can also set an alternative path to the blast executable with `--blast-path`

**Comment by kishore556** [comment]
Thanks Pirovc
The 'makeblastdb' command is fine as BLAST is running properly. The problem was with file libstdc++.so.6 in MCR folder. That library file was symlinked from main library folder. That worked well.
Thanks
